use ruffle_core::events::KeyCode;
use winit::event::KeyEvent;
use winit::keyboard::Key;
use winit::keyboard::KeyLocation;
use winit::keyboard::NamedKey;

/// Convert a winit event into a Ruffle `KeyCode`.
/// Return `KeyCode::Unknown` if there is no matching Flash key code.
pub fn winit_to_ruffle_key_code(event: &KeyEvent) -> KeyCode {
    match event.logical_key.as_ref() {
        Key::Named(NamedKey::Backspace) => KeyCode::Backspace,
        Key::Named(NamedKey::Tab) => KeyCode::Tab,
        Key::Named(NamedKey::Enter) => KeyCode::Return,
        Key::Named(NamedKey::Shift) => KeyCode::Shift,
        Key::Named(NamedKey::Control) => KeyCode::Control,
        Key::Named(NamedKey::Alt) => KeyCode::Alt,
        Key::Named(NamedKey::CapsLock) => KeyCode::CapsLock,
        Key::Named(NamedKey::Escape) => KeyCode::Escape,
        Key::Named(NamedKey::Space) => KeyCode::Space,
        Key::Character("0") if event.location == KeyLocation::Numpad => KeyCode::Numpad0,
        Key::Character("1") if event.location == KeyLocation::Numpad => KeyCode::Numpad1,
        Key::Character("2") if event.location == KeyLocation::Numpad => KeyCode::Numpad2,
        Key::Character("3") if event.location == KeyLocation::Numpad => KeyCode::Numpad3,
        Key::Character("4") if event.location == KeyLocation::Numpad => KeyCode::Numpad4,
        Key::Character("5") if event.location == KeyLocation::Numpad => KeyCode::Numpad5,
        Key::Character("6") if event.location == KeyLocation::Numpad => KeyCode::Numpad6,
        Key::Character("7") if event.location == KeyLocation::Numpad => KeyCode::Numpad7,
        Key::Character("8") if event.location == KeyLocation::Numpad => KeyCode::Numpad8,
        Key::Character("9") if event.location == KeyLocation::Numpad => KeyCode::Numpad9,
        Key::Character("0") => KeyCode::Key0,
        Key::Character("1") => KeyCode::Key1,
        Key::Character("2") => KeyCode::Key2,
        Key::Character("3") => KeyCode::Key3,
        Key::Character("4") => KeyCode::Key4,
        Key::Character("5") => KeyCode::Key5,
        Key::Character("6") => KeyCode::Key6,
        Key::Character("7") => KeyCode::Key7,
        Key::Character("8") => KeyCode::Key8,
        Key::Character("9") => KeyCode::Key9,
        Key::Character("a") => KeyCode::A,
        Key::Character("b") => KeyCode::B,
        Key::Character("c") => KeyCode::C,
        Key::Character("d") => KeyCode::D,
        Key::Character("e") => KeyCode::E,
        Key::Character("f") => KeyCode::F,
        Key::Character("g") => KeyCode::G,
        Key::Character("h") => KeyCode::H,
        Key::Character("i") => KeyCode::I,
        Key::Character("j") => KeyCode::J,
        Key::Character("k") => KeyCode::K,
        Key::Character("l") => KeyCode::L,
        Key::Character("m") => KeyCode::M,
        Key::Character("n") => KeyCode::N,
        Key::Character("o") => KeyCode::O,
        Key::Character("p") => KeyCode::P,
        Key::Character("q") => KeyCode::Q,
        Key::Character("r") => KeyCode::R,
        Key::Character("s") => KeyCode::S,
        Key::Character("t") => KeyCode::T,
        Key::Character("u") => KeyCode::U,
        Key::Character("v") => KeyCode::V,
        Key::Character("w") => KeyCode::W,
        Key::Character("x") => KeyCode::X,
        Key::Character("y") => KeyCode::Y,
        Key::Character("z") => KeyCode::Z,
        Key::Character(";") => KeyCode::Semicolon,
        Key::Character("=") => KeyCode::Equals,
        Key::Character(",") => KeyCode::Comma,
        Key::Character("-") if event.location == KeyLocation::Numpad => KeyCode::NumpadMinus,
        Key::Character("-") => KeyCode::Minus,
        Key::Character(".") if event.location == KeyLocation::Numpad => KeyCode::NumpadPeriod,
        Key::Character(".") => KeyCode::Period,
        Key::Character("/") if event.location == KeyLocation::Numpad => KeyCode::NumpadSlash,
        Key::Character("/") => KeyCode::Slash,
        Key::Character("`") => KeyCode::Grave,
        Key::Character("[") => KeyCode::LBracket,
        Key::Character("\\") => KeyCode::Backslash,
        Key::Character("]") => KeyCode::RBracket,
        Key::Character("'") => KeyCode::Apostrophe,
        Key::Character("*") => KeyCode::Multiply,
        Key::Character("+") => KeyCode::Plus,
        Key::Named(NamedKey::PageUp) => KeyCode::PgUp,
        Key::Named(NamedKey::PageDown) => KeyCode::PgDown,
        Key::Named(NamedKey::End) => KeyCode::End,
        Key::Named(NamedKey::Home) => KeyCode::Home,
        Key::Named(NamedKey::ArrowLeft) => KeyCode::Left,
        Key::Named(NamedKey::ArrowUp) => KeyCode::Up,
        Key::Named(NamedKey::ArrowRight) => KeyCode::Right,
        Key::Named(NamedKey::ArrowDown) => KeyCode::Down,
        Key::Named(NamedKey::Insert) => KeyCode::Insert,
        Key::Named(NamedKey::Delete) => KeyCode::Delete,
        Key::Named(NamedKey::Pause) => KeyCode::Pause,
        Key::Named(NamedKey::ScrollLock) => KeyCode::ScrollLock,
        Key::Named(NamedKey::F1) => KeyCode::F1,
        Key::Named(NamedKey::F2) => KeyCode::F2,
        Key::Named(NamedKey::F3) => KeyCode::F3,
        Key::Named(NamedKey::F4) => KeyCode::F4,
        Key::Named(NamedKey::F5) => KeyCode::F5,
        Key::Named(NamedKey::F6) => KeyCode::F6,
        Key::Named(NamedKey::F7) => KeyCode::F7,
        Key::Named(NamedKey::F8) => KeyCode::F8,
        Key::Named(NamedKey::F9) => KeyCode::F9,
        Key::Named(NamedKey::F10) => KeyCode::F10,
        Key::Named(NamedKey::F11) => KeyCode::F11,
        Key::Named(NamedKey::F12) => KeyCode::F12,
        Key::Named(NamedKey::F13) => KeyCode::F13,
        Key::Named(NamedKey::F14) => KeyCode::F14,
        Key::Named(NamedKey::F15) => KeyCode::F15,
        Key::Named(NamedKey::F16) => KeyCode::F16,
        Key::Named(NamedKey::F17) => KeyCode::F17,
        Key::Named(NamedKey::F18) => KeyCode::F18,
        Key::Named(NamedKey::F19) => KeyCode::F19,
        Key::Named(NamedKey::F20) => KeyCode::F20,
        Key::Named(NamedKey::F21) => KeyCode::F21,
        Key::Named(NamedKey::F22) => KeyCode::F22,
        Key::Named(NamedKey::F23) => KeyCode::F23,
        Key::Named(NamedKey::F24) => KeyCode::F24,
        _ => KeyCode::Unknown,
    }
}
