/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bruenor_magicbox_MagicLauncher_DosBoxThread */

#ifndef _Included_bruenor_magicbox_MagicLauncher_DosBoxThread
#define _Included_bruenor_magicbox_MagicLauncher_DosBoxThread
#ifdef __cplusplus
extern "C" {
#endif
#undef bruenor_magicbox_MagicLauncher_DosBoxThread_MIN_PRIORITY
#define bruenor_magicbox_MagicLauncher_DosBoxThread_MIN_PRIORITY 1L
#undef bruenor_magicbox_MagicLauncher_DosBoxThread_NORM_PRIORITY
#define bruenor_magicbox_MagicLauncher_DosBoxThread_NORM_PRIORITY 5L
#undef bruenor_magicbox_MagicLauncher_DosBoxThread_MAX_PRIORITY
#define bruenor_magicbox_MagicLauncher_DosBoxThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
