/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bruenor_magicbox_MagicLauncher */

#ifndef _Included_bruenor_magicbox_MagicLauncher
#define _Included_bruenor_magicbox_MagicLauncher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeMouseMax
 * Signature: (ZII)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeMouseMax
  (JNIEnv *, jclass, jboolean, jint, jint);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeSetAbsoluteMouseType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeSetAbsoluteMouseType
  (JNIEnv *, jclass, jint);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeMouseRoundMaxByVideoMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeMouseRoundMaxByVideoMode
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeGetMouseMaxX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bruenor_magicbox_MagicLauncher_nativeGetMouseMaxX
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeGetMouseMaxY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bruenor_magicbox_MagicLauncher_nativeGetMouseMaxY
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeGetMouseVideoWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bruenor_magicbox_MagicLauncher_nativeGetMouseVideoWidth
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeGetMouseVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bruenor_magicbox_MagicLauncher_nativeGetMouseVideoHeight
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeSaveState
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeSaveState
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeLoadState
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeLoadState
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeShutDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeShutDown
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeSetOption
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeSetOption
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeStart
 * Signature: (Ljava/nio/Buffer;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeStart
  (JNIEnv *, jobject, jobject, jint, jint, jstring);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativePause
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativePause
  (JNIEnv *, jclass, jint);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeStop
  (JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeForceStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bruenor_magicbox_MagicLauncher_nativeForceStop
(JNIEnv *, jclass);

/*
 * Class:     bruenor_magicbox_MagicLauncher
 * Method:    nativeGetLibArchitecture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bruenor_magicbox_MagicLauncher_nativeGetLibArchitecture
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
